### ISSUE TITLE
Netrunner Core IMG - Checklist (keep open)

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-core-releases#50]
c1 img installed programs (20+calamares=21):
![Snap 2019-04-13 at 14 12 45](https://user-images.githubusercontent.com/840070/56079591-27f23200-5df7-11e9-9457-91121cd8df3e.png)

**graphics**:
* gwenview

**internet**:
* firefox
* x11vncserver

**multimedia**:
* pulseaudio volume control

**office**:
* okular (should go to utilities)

**settings**:
* system settings

**system**:
* (calamares)
* dolphin
* info center
* kde partition manager
* konsole
* ksysguard
* kwallet manager
* network drives
* synaptic package manager
* update manager
* yakuake

**utilities**:
* ark
* kate
* kcalc
* spectacle

----
Basic Tests:
- [x]  installation works?
- [x] german install works?
plasma:
- [x] meta key works?
- [x] tty1 - tty7 ALT+STRG+F1 - F7
- [x] drag windows from titlebar 
programs:
- [x] firefox loads, addons are there 
- [x] synaptic repo list okay, refresh does not throw errors 

----

- [x] Correct panel and desktop comes up
- [x] Right click menu configured correctly
- [x] Every app starts
- [x] Mintupdate starts and software-properties is accessible
- [x] Synaptic installing qmmp app works
- [x] Version + Artwork are correct
- [x] Firefox configuration correct
- [x] Firefox does not crash when opening urls
- [x] Firefox does not crash when watching videos
- [x] Installation works
- [x] Localization works
- [x] Sound works
- [x] Network connection works
- [x] apt-get does not throw errors
- [x] sddm artwork is correct
- [x] reboot, shutdown sysactions work without extra menu

**Comment by star-buck** [comment]
current c1 img has 19 programs, is missing Update Manager and suse img writer
