### ISSUE TITLE
Netrunner Core ISO - Checklist (keep open)

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-core-releases#52]
Installed programs (21+calamares=22):
![Snap 2019-04-13 at 14 12 45](https://user-images.githubusercontent.com/840070/56079538-5f141380-5df6-11e9-90df-fd55e9df1b53.png)

**graphics**:
* gwenview

**internet**:
* firefox
* x11vncserver

**multimedia**:
* pulseaudio volume control

**office**:
* okular (should go to utilities)

**settings**:
* system settings

**system**:
* (calamares)
* dolphin
* info center
* kde partition manager
* konsole
* ksysguard
* kwallet manager
* network drives
* synaptic package manager
* update manager
* yakuake

**utilities**:
* ark
* kate
* kcalc
* spectacle
* Suse ImageWriter

----
Basic Tests:
- [x]  installation works?
- [x] german install works?
- [ ] uefi install works? 
plasma:
- [x] meta key works?
- [x] tty1 - tty7 ALT+STRG+F1 - F7
- [x] drag windows from titlebar 
programs:
- [x] firefox loads, addons are there 
- [x] synaptic repo list okay, refresh does not throw errors 

----

- [x] Correct panel and desktop comes up
- [x] Right click menu configured correctly
- [ ] Every app starts
- [ ] Mintupdate starts and software-properties is accessible
- [ ] Synaptic installing qmmp app works
- [x] Version + Artwork are correct
- [x] Firefox configuration correct
- [x] Firefox does not crash when opening urls
- [x] Firefox does not crash when watching videos
- [ ] Thunderbirds starts with calendar addon
- [x] Installation works
- [x] Localization works
- [x] Sound works
- [x] Network connection works
- [x] apt-get does not throw errors
- [x] sddm artwork is correct
- [x] reboot, shutdown sysactions work without extra menu
